version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
